version: 2.1

version-tag-only: &version-tag-only
  tags:
    only: /^v[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}$/
  branches:
    ignore: /.*/

schedule-trigger: &schedule-trigger
  equal: [ scheduled_pipeline, << pipeline.trigger_source >> ]

not-schedule-trigger: &not-schedule-trigger
  not:
    *schedule-trigger

orbs:
  c: rafaelostertag/common-orb@1.19.0

workflows:
  build-any-branch:
    when:
      *not-schedule-trigger
    jobs:
      - c/maven-build-and-test:
          name: build-and-test
          sonar-project-key: "ch.guengel:imageserver"
          context:
            - sonar
            - repository-read

  build-and-release:
    when:
      *not-schedule-trigger
    jobs:
      - c/maven-build-and-test:
          name: build-and-test
          sonar-project-key: "ch.guengel:imageserver"
          context:
            - sonar
            - repository-read
          filters:
            *version-tag-only
      - c/maven-deploy-artifacts:
          name: deploy-maven-artifact
          requires:
            - build-and-test
          context:
            - maven-repository-write
          filters:
            *version-tag-only
      - c/maven-quarkus-docker-image:
          name: docker-image-amd64
          executor: c/java11-build-amd64
          dir: "."
          context:
            - repository-read
            - docker-build
          requires:
            - deploy-maven-artifact
          filters:
            *version-tag-only
      - c/maven-quarkus-docker-image:
          name: docker-image-arm64
          executor: c/java11-build-arm64
          remote_docker: false
          dir: "."
          context:
            - repository-read
            - docker-build
          requires:
            - deploy-maven-artifact
          filters:
            *version-tag-only
      - c/maven-multi-arch-manifest:
          name: build-multi-arch-manifest
          image: "rafaelostertag/imageserver"
          context:
            - docker-build
          requires:
            - docker-image-arm64
            - docker-image-amd64
          filters:
            *version-tag-only
      - c/maven-trigger-pipeline-with-version:
          name: trigger-helm-deployment
          project-name: imageserver-helm
          context:
            - circle-ci
          requires:
            - build-multi-arch-manifest
          filters:
            *version-tag-only
  
  daily-dependency-check:
    when:
      *schedule-trigger
    jobs:
      - c/maven-dependency-check:
          context:
            - repository-read
