version: 2.1

tag-filter: &tagfilter
  tags:
    only: /^v[0-9]{1,2}\.[0-9]{1,2}\.[0-9]{1,2}$/


orbs:
  c: rafaelostertag/common-orb@1.19.0

workflows:
  build-any-branch:
    jobs:
      - c/maven-build-and-test:
          name: build-and-test
          sonar-project-key: "ch.guengel:imageserver"
          context:
            - sonar
            - repository-read

  build-and-release:
    jobs:
      - c/maven-build-and-test:
          name: build-and-test
          sonar-project-key: "ch.guengel:imageserver"
          context:
            - sonar
            - repository-read
          filters:
            *tagfilter
      - c/maven-deploy-artifacts:
          name: deploy-maven-artifact
          requires:
            - build-and-test
          context:
            - maven-repository-write
          filters:
            *tagfilter
      - c/maven-quarkus-docker-image:
          name: docker-image-amd64
          executor: c/java11-build-amd64
          dir: "."
          context:
            - repository-read
            - docker-build
          requires:
            - deploy-maven-artifact
          filters:
            *tagfilter
      - c/maven-quarkus-docker-image:
          name: docker-image-arm64
          executor: c/java11-build-arm64
          remote_docker: false
          dir: "."
          context:
            - repository-read
            - docker-build
          requires:
            - deploy-maven-artifact
          filters:
            *tagfilter
      - c/maven-multi-arch-manifest:
          name: build-multi-arch-manifest
          image: "rafaelostertag/imageserver"
          context:
            - docker-build
          requires:
            - docker-image-arm64
            - docker-image-amd64
          filters:
            *tagfilter
      - c/maven-trigger-pipeline-with-version:
          name: trigger-helm-deployment
          project-name: imageserver-helm
          context:
            - circle-ci
          requires:
            - build-multi-arch-manifest
          filters:
            *tagfilter
  
  daily-dependency-check:
    triggers:
      - schedule:
          cron: "21 4 * * 4"
          filters:
            branches:
              only:
                - master
                - develop

    jobs:
      - c/maven-dependency-check:
          context:
            - repository-read
